---
- name: Check packer install
  command: which /usr/local/packer/bin/packer
  ignore_errors: True
  register: packer_result

- name: Extract archive
  unarchive:
    src: https://releases.hashicorp.com/packer/1.0.0/packer_1.0.0_linux_amd64.zip
    dest: /usr/local/src/
    remote_src: true
    owner: root
    group: root
  when: packer_result|failed

- name: Create packer install directory
  file:
    path: /usr/local/packer/bin
    state: directory
    recurse: yes
    owner: root
    group: root
    mode: 0755
  when: packer_result|failed

- name: Copy packer command
  copy:
    src: /usr/local/src/packer
    dest: /usr/local/packer/bin/packer
    directory_mode: True
    owner: root
    group: root
    mode: 0755
  when: packer_result|failed

